version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:lts

jobs:
  build:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          npm install
          npm build
  publish:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: |
          docker build . -t dams38/node-web-app
          docker image push dams38/node-web-app

workflows:
  my-custom-workflow:
    jobs:
      - build
      - publish