version: 2.1
executors:
  dams-executor:
    docker:
      - image: cimg/node:lts

jobs:
  build:
    executor: dams-executor
    steps:
      - checkout
      - run: |
          npm install
          npm build
  publish:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: |
          docker login --username dams38 -p $DOCKER_PASSWORD
          docker build . -t dams38/node-web-app
          docker image push dams38/node-web-app

workflows:
  dams-executor:
    jobs:
      - build
      - publish:
          requires:
            - build